Removed redundant SubcomposeLayout in favor of Layout
onebone/compose-collapsing-toolbar pull request #26
Opened 2021-12-16 09:39 UTC by RareScrap

Fix of #23 and #11

2021-12-20 16:13 UTC, onebone commented
Sorry for the review being late, I think it will take some time. I will do it as soon as possible.

2021-12-25 15:01 UTC, onebone requested changes

2021-12-28 14:06 UTC, RareScrap commented on lib/src/main/java/me/onebone/toolbar/CollapsingToolbarScaffold.kt
> -			}
I did just that - moved the toolbar to the top

2021-12-28 14:06 UTC, RareScrap commented on lib/src/main/java/me/onebone/toolbar/CollapsingToolbarScaffold.kt
> +			measurables.drop(1).map { it.measure(bodyConstraints) }// [1].measure(bodyConstraints)
No, I just forgot to put it away. Fixed

2022-01-01 13:33 UTC, onebone requested changes

2022-01-01 13:33 UTC, onebone commented on lib/src/main/java/me/onebone/toolbar/CollapsingToolbarScaffold.kt
> -			}
Sorry for the confusion, what I meant by _top_ was from the layout perspective. Compose puts the first one to the bottom like a stack.

![image](https://user-images.githubusercontent.com/3233503/147851561-17da15b8-9625-41a9-8652-97a0aef5b972.png)
![image](https://user-images.githubusercontent.com/3233503/147851569-9ce7688c-c6bf-4b28-84a6-9baef334e894.png)

2022-01-01 13:33 UTC, onebone commented on lib/src/main/java/me/onebone/toolbar/CollapsingToolbarScaffold.kt
> +			measurables.drop(1).map { it.measure(bodyConstraints) }// [1].measure(bodyConstraints)
Sorry for the confusion, what I meant by _top_ was from the layout perspective. Compose puts the first one to the bottom like a stack.

![image](https://user-images.githubusercontent.com/3233503/147851561-17da15b8-9625-41a9-8652-97a0aef5b972.png)
![image](https://user-images.githubusercontent.com/3233503/147851569-9ce7688c-c6bf-4b28-84a6-9baef334e894.png)

2022-01-01 13:36 UTC, onebone commented on lib/src/main/java/me/onebone/toolbar/CollapsingToolbarScaffold.kt
> -			}
Sorry for the confusion, what I meant by _top_ was from the layout perspective. Compose puts the first one to the bottom like a stack.

![image](https://user-images.githubusercontent.com/3233503/147851561-17da15b8-9625-41a9-8652-97a0aef5b972.png)
![image](https://user-images.githubusercontent.com/3233503/147851569-9ce7688c-c6bf-4b28-84a6-9baef334e894.png)

2022-01-04 04:08 UTC, RareScrap commented on lib/src/main/java/me/onebone/toolbar/CollapsingToolbarScaffold.kt
> -			}
Fixed. Thank you for notice this.

2022-01-04 18:56 UTC, toddrandy79 commented on lib/src/main/java/me/onebone/toolbar/CollapsingToolbarScaffold.kt
> -			}
Good job

2022-01-05 15:02 UTC, onebone approved these changes
Thank you for your contribution! I was actually quite confused about what SubcomposeLayout was for and thought of it as a graceful way to create a slot in layout. I appreciate your hard research work and this contribution for making me clear of the concept 😃 😃 👍 👍

2022-01-05 15:02 UTC, merged